### ISSUE TITLE
Features are 0: Step 7 unsupervised_tuning

### ISSUE THREAD

**Issue by yvonnegitau** [artetxem/monoses#5] opened 2019-03-22 14:58 UTC
@artetxem Great work on the project. I am trying to reproduce your results but cant get past step 7
I am using wmt14 news.2010 french and english text. After the first iteration of step 7 the features in the features list are all 0. Therefore throwing an error of Illegal division by zero at moses/scripts/training/mert-moses.pl line 1290

I have tried with other datasets but still getting the same error

**Comment by artetxem** [comment] 2019-03-25 13:52
Looks like a duplicate of #3 . Make sure that Moses is properly compiled (e.g. moses2 should exist under bin).

**Comment by yvonnegitau** [comment] 2019-04-01 13:05
Thanks for that. Used the binary file of moses and it worked

**Closed** 2019-04-16 13:01 UTC
